name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag scys/wallchat:latest
        docker login --user ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_TOKEN }}
        docker push --tag scys/wallchat:latest
